# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_study/',
                'doc_host': 'https://inodie.github.io',
                'git_url': 'https://github.com/inodie/fastai-study/',
                'lib_path': 'fastai_study'},
  'syms': {'fastai_study.core': {'fastai_study.core.check_env': ('core.html#check_env', 'fastai_study/core.py')}}}
