"""fastai를 이용해 개와 고양이를 분류합니다."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_cat dog find.ipynb.

# %% auto 0
__all__ = ['path', 'dls', 'learn', 'is_cat']

# %% ../01_cat dog find.ipynb 3
from fastai.vision.all import *

path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = vision_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)
