"""fastai 학습을 위한 기초 함수들을 정의합니다."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['check_env']

# %% ../00_core.ipynb 2
from fastai.vision.all import *

def check_env():
    "환경 설정이 잘 되었는지 확인하는 함수입니다."
    print("fastai와 nbdev 연동 성공!")
