"""fastai를 이용해 세그먼테이션 모델을 학습시키는 방법입니다."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_segmentation.ipynb.

# %% auto 0
__all__ = ['path', 'dls', 'learn']

# %% ../02_segmentation.ipynb 2
from fastai.vision.all import *

path = untar_data(URLs.CAMVID_TINY)

dls = SegmentationDataLoaders.from_label_func(
    path, bs=8, fnames=get_image_files(path/"images"),
    label_func=lambda o: path/'labels' /f'{o.stem}_P{o.suffix}',
    codes=np.loadtxt(path/'codes.txt', dtype=str)
)

learn = unet_learner(dls, resnet34)
learn.fine_tune(8)
