"""fastai를 이용해 tabular 모델을 학습시키는 방법입니다."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_tabular.ipynb.

# %% auto 0
__all__ = ['path', 'dls', 'learn']

# %% ../03_tabular.ipynb 2
from fastai.tabular.all import *

path = untar_data(URLs.ADULT_SAMPLE)

dls = TabularDataLoaders.from_csv(
    path/'adult.csv', path=path, y_names="salary",
    cat_name=['workclass','education','marital-status','occupation',
              'relationship','race'],
    cont_names=['age','fnlwgt','education-num'],
    procs=[Categorify, FillMissing, Normalize])

learn = tabular_learner(dls, metrics=accuracy)
learn.fit_one_cycle(3)
